---
- name: Create directories for syrup
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
  with_items:
    - "{{ syrup_deploy_dir }}"
  become: true

- name: Check if repo exists
  stat:
    path: "{{ syrup_deploy_dir }}/.git"
  register: dir_stat

- name: Clone repo
  command: git clone {{ syrup_repo_url }} {{ syrup_deploy_dir }}
  environment:
    GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
  when: dir_stat.stat.exists == false

- name: Pull repo
  command:
    argv:
      - "git"
      - "pull"
    chdir: "{{ syrup_deploy_dir }}"
  when: dir_stat.stat.exists == true

- name: Render docker-compose file
  template:
    src: "docker-compose.yml"
    dest: "{{ syrup_deploy_dir }}/docker-compose.yml"
    mode: 0644
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
  become: true
