---
- name: Start coffee-service
  command:
    argv:
      - "docker"
      - "compose"
      - "-f"
      - "{{ coffee_deploy_dir }}/docker-compose.yml"
      - "-p"
      - "coffee"
      - "up"
      - "-d"
      - "--no-build"
      - "--force-recreate"
  become: true