---
- name: Start drink-service
  command:
    argv:
      - "docker"
      - "compose"
      - "-f"
      - "{{ drink_deploy_dir }}/docker-compose.yml"
      - "-p"
      - "drink"
      - "up"
      - "-d"
      - "--no-build"
      - "--force-recreate"
  become: true