---
- name: Stop drink
  command:
    argv:
      - "docker"
      - "compose"
      - "-f"
      - "{{ drink_deploy_dir }}/docker-compose.yml"
      - "-p"
      - "drink"
      - "down"
  become: true