version: "3.5"

services:
  maple-syrup:
    image: syrup:{{ syrup_tag }}
    environment:
      - PORT=80
      - SYRUP_TYPE=maple
    ports:
    - 3001:80

  strawberry-syrup:
    image: syrup:{{ syrup_tag }}
    environment:
      - PORT=80
      - SYRUP_TYPE=strawberry
    ports:
    - 3002:80

  vanilla-syrup:
    image: syrup:{{ syrup_tag }}
    environment:
      - PORT=80
      - SYRUP_TYPE=vanilla
    ports:
    - 3003:80 
  banana-syrup:
    image: syrup:{{ syrup_tag }}
    environment:
      - PORT=80
      - SYRUP_TYPE=banana
    ports:
    - 3004:80