---
- name: Start master_lb-service
  command:
    argv:
      - "docker"
      - "compose"
      - "-f"
      - "{{ master_lb_deploy_dir }}/docker-compose.yml"
      - "-p"
      - "master_lb"
      - "up"
      - "-d"
      - "--no-build"
      - "--force-recreate"
  become: true