---
- name: Stop master_lb
  command:
    argv:
      - "docker"
      - "compose"
      - "-f"
      - "{{ master_lb_deploy_dir }}/docker-compose.yml"
      - "-p"
      - "master_lb"
      - "down"
  become: true