version: "3.5"

services:
  original-milk:
    image: milk:{{ milk_tag }}
    environment:
      - PORT=80
      - MILK_TYPE=original
    ports:
    - 3001:80

  almond-milk:
    image: milk:{{ milk_tag }}
    environment:
      - PORT=80
      - MILK_TYPE=almond
    ports:
    - 3002:80

  coconut-milk:
    image: milk:{{ milk_tag }}
    environment:
      - PORT=80
      - MILK_TYPE=coconut
    ports:
    - 3003:80
