#cloud-config
hostname: ${ hostname}

package_update: true
packages:
  - git
  - htop
  - python3
  - pip
  - vim

users:
  - name: fedorov
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    plain_text_passwd: ${ ssh_pass }

runcmd:
  - apt-get update && apt install -y firewalld
  - /usr/bin/firewall-offline-cmd --new-zone=nat
  - /usr/bin/firewall-offline-cmd --set-default-zone=nat
  - /usr/bin/firewall-offline-cmd --zone=nat --add-source=0.0.0.0/0
  - /usr/bin/firewall-offline-cmd --zone=nat --add-masquerade
  - /usr/bin/firewall-offline-cmd --zone=nat --add-service=ssh
  - /usr/bin/firewall-offline-cmd --zone=nat --add-forward-port=port=1900:proto=tcp:toport=22:toaddr=192.168.7.100
  - /usr/bin/firewall-offline-cmd --zone=nat --add-forward-port=port=1901:proto=tcp:toport=22:toaddr=192.168.7.101
  - /usr/bin/firewall-offline-cmd --zone=nat --add-forward-port=port=1902:proto=tcp:toport=22:toaddr=192.168.7.102
  - /usr/bin/firewall-offline-cmd --zone=nat --add-forward-port=port=1903:proto=tcp:toport=22:toaddr=192.168.7.103
  - /usr/bin/firewall-offline-cmd --zone=nat --add-forward-port=port=1904:proto=tcp:toport=22:toaddr=192.168.7.104
  - /bin/systemctl enable firewalld
  - /bin/systemctl start firewalld
  - /usr/bin/firewall-cmd --reload