port: 80
groups:
  - alias: milk
    endpoints:
    - url: http://192.168.7.103:3001
      weight: 3
    - url: http://192.168.7.103:3002
      weight: 1
    - url: http://192.168.7.103:3003
      weight: 2
  - alias: drink
    endpoints:
    - url: http://192.168.7.102:3001
      weight: 1
    - url: http://192.168.7.102:3002
      weight: 1
  - alias: syrup
    endpoints:
    - url: http://192.168.7.104:3001
      weight: 4
    - url: http://192.168.7.104:3002
      weight: 2
    - url: http://192.168.7.104:3003
      weight: 3
    - url: http://192.168.7.104:3004
      weight: 2