version: "3.5"

services:
  lb-master:
    image: master-lb:{{ master_lb_tag }}
    environment:
      - CONFIG_PATH=/app/config/config.yml
    volumes:
      - "./config.yml:/app/config/config.yml"
    ports:
      - 9000:80